Repository jenkinsci/conditional-buildstep-plugin, pull requests merged in 2020-11, with the labels that each got.

#20 migrate wiki documentation to github
  CHANGELOG.adoc
  README.adoc
  README.md
  docs/images/screen-capture-1.jpg
  docs/images/screen-capture-2.jpg
  pom.xml
Labels: documentation

#21 [JENKINS-62910] Table to div compatibility
  .mvn/extensions.xml
  .mvn/maven.config
  pom.xml
  src/main/resources/lib/conditionalbuildstep/blockWrapper.jelly
  src/main/resources/lib/conditionalbuildstep/taglib
  src/main/resources/org/jenkinsci/plugins/conditionalbuildstep/ConditionalBuilder/config.jelly
Labels: enhancement

#22 Polish the documentation after migration to GitHub
  README.adoc
Labels: documentation

#23 Add Release Drafter configuration
  .github/release-drafter.yml
  .github/workflows/changelog.yml
Labels: chore
